config/routes.rb
Rails.application.routes.draw do
  resources :lookups
  root 'lookups#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lookup.rb
class Lookup < ApplicationRecord
  validates_presence_of :slug

  def to_param
    slug
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  before_action :set_lookup, only: [:show, :edit, :update, :destroy]
  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
  end

  # GET /lookups/new
  def new
    @lookup = Lookup.new
  end

  # GET /lookups/1/edit
  def edit
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(lookup_params)
    @lookup.slug = @lookup.address.downcase.gsub(" ", "_")
    @lookup.save

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render :show, status: :created, location: @lookup }
      else
        format.html { render :new }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lookups/1
  # PATCH/PUT /lookups/1.json
  def update
    respond_to do |format|
      if @lookup.update(lookup_params)
        format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
        format.json { render :show, status: :ok, location: @lookup }
      else
        format.html { render :edit }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup.destroy
    respond_to do |format|
      format.html { redirect_to lookups_url, notice: 'Lookup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lookup
      @lookup = Lookup.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lookup_params
      params.require(:lookup).permit(:address, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ffhome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lookups/_form.html.erb
<%= form_with(model: lookup, local: true) do |form| %>
  <% if lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
      <% lookup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lookups/edit.html.erb
<h1>Editing Lookup</h1>

<%= render 'form', lookup: @lookup %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Here are the Lookups</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lookups.each do |lookup| %>
      <tr>
        <td><%= lookup.address %></td>
        <td><%= link_to 'Show', lookup %></td>
        <td><%= link_to 'Edit', edit_lookup_path(lookup) %></td>
        <td><%= link_to 'Destroy', lookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lookup', new_lookup_path %>

app/views/lookups/new.html.erb
<h1>New Lookup</h1>

<%= render 'form', lookup: @lookup %>

<%= link_to 'Back', lookups_path %>

app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @lookup.address %>
</p>

<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>